### ISSUE TITLE
Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-4#1]
I've been struggling with storing objects into currents state in React, and keep hitting this error that is preventing me from dynamically rendering information. I can rend one specific value if I use dot notation to set the state specifically to that value, but can't do anything else... which is unhelpful. 

http://mediatemple.net/blog/tips/loading-and-using-external-data-in-react/
https://stackoverflow.com/questions/37997893/promise-error-objects-are-not-valid-as-a-react-child

**Comment by ZebGirouard** [comment]
Asynchronicity strikes again!  Keep it up, Jacy.
